fix(local/bin/task-sync): add std error to log

diff --git a/.local/bin/task-sync b/.local/bin/task-sync
--- a/.local/bin/task-sync
+++ b/.local/bin/task-sync
@@ -17,7 +17,7 @@ if tmux has-session -t $TMUX_SESSION 2>/dev/null; then
 fi
 
 # create tmux session, and start sync
-tmux new-session -d -s $TMUX_SESSION "sleep $DELAY && echo \"\$(date \"+%F %T\") \$(task sync)\" >>$SYNC_LOG || echo 'Sync failed'" 
+tmux new-session -d -s $TMUX_SESSION "sleep $DELAY && echo \"\$(date \"+%F %T\") \$(task sync)\" >>$SYNC_LOG &>1 || echo 'Sync failed'" 
 
 if [ "$(wc -l $SYNC_LOG | awk '{print $1}')" -gt 1000 ]; then
 	sed -i '1,500d' $SYNC_LOG
